### ISSUE TITLE
Could not find remote branch: refs/heads/master

### ISSUE THREAD

**Issue by JustinBarker** [kerwinc/VSTSTasks#3]
Using "Visual Studio Team Services":
I setup a build to check out my repository and ran the "Gitflow Branch Gate" and got the error "Could not find remote branch: refs/heads/master"

I did set the Authentication to be Windows Authentication. (Which our build servers run as to access the code and other resources)

Am I missing some setup?

**Comment by GraemeSMiller** [comment]
For me in VSTS (on private agent) the fix was to use OAuthToken and then set Allow scripts to access OAuth token

**Comment by kerwinc** [comment]
Hey Justin, 

Apologies for replying a year later. Life got away with me :). I am in the process of updating this build task. I presume you got this working? This error was explicitly thrown as it couldn't find your master branch. 

For anyone else having this issue, check that the "Master Branch" defined in the task's settings (default is master) exists as a git repo in the VSTS project.

**Comment by JustinBarker** [comment]
I tried this again using @GraemeSMiller s suggestion. 
Checking the "Allow scripts to access OAuth token" fixed it for me.
Thanks!

**Comment by soerennielsen** [comment]
> 
> 
> I tried this again using @GraemeSMiller s suggestion.
> Checking the "Allow scripts to access OAuth token" fixed it for me.
> Thanks!

Yep, that does the trick :-)

**Comment by evaldezb** [comment]
@kerwinc sorry I bring this up again but is there any news with this? I can't find the option for "Allow scripts to access OAuth token" on Azure DevOps and the master branch does exist in the remote. Is there any other approach?

I downloaded the extension from the azure market place, is that one up to date with this?

```
- task: GitflowBranchGate@1
  displayName: 'GitFlow Compliance'
  inputs:
    repository: '$(Build.Repository.Name)'
    masterBranch: 'master'
    developBranch: 'develop'
    hotfixBranches: 'hotfix/*'
    releaseBranches: 'release/*'
    featureBranches: 'feature/*'
    hotfixBranchLimit: '1'
    hotfixBranchDaysLimit: '15'
    releaseBranchLimit: '1'
    releaseBranchDaysLimit: '10'
    featureBranchLimit: '5'
    featureBranchDaysLimit: '80'
    featureBranchesMustNotBeBehindDevelop: true
    authenticationType: 'OAuthToken'
```

**Comment by evaldezb** [comment]
> @kerwinc sorry I bring this up again but is there any news with this? I can't find the option for "Allow scripts to access OAuth token" on Azure DevOps and the master branch does exist in the remote. Is there any other approach?
> 
> I downloaded the extension from the azure market place, is that one up to date with this?
> 
> ```
> - task: GitflowBranchGate@1
>   displayName: 'GitFlow Compliance'
>   inputs:
>     repository: '$(Build.Repository.Name)'
>     masterBranch: 'master'
>     developBranch: 'develop'
>     hotfixBranches: 'hotfix/*'
>     releaseBranches: 'release/*'
>     featureBranches: 'feature/*'
>     hotfixBranchLimit: '1'
>     hotfixBranchDaysLimit: '15'
>     releaseBranchLimit: '1'
>     releaseBranchDaysLimit: '10'
>     featureBranchLimit: '5'
>     featureBranchDaysLimit: '80'
>     featureBranchesMustNotBeBehindDevelop: true
>     authenticationType: 'OAuthToken'
> ```

Thing is that the default way of Azure Devops to create pipelines is with YAML and in order for this to work it need to be inside a JOB and with the option "Allow scripts to access OAuth token" checked. 

1. That being said, when creating a new pipeline is necessary to select "Use the classic editor..."
![image](https://user-images.githubusercontent.com/32545163/67570514-99dcf980-f6ff-11e9-80fe-42684b8a5092.png)

1. Select an empty job:
![image](https://user-images.githubusercontent.com/32545163/67570578-c55fe400-f6ff-11e9-91f5-473570141644.png)

1. Select the option "Allow scripts to access OAuth token"
![image](https://user-images.githubusercontent.com/32545163/67570438-65693d80-f6ff-11e9-8f3a-a48028fc0526.png)

1. And add the GitFlow Branch Gate to the job:
![image](https://user-images.githubusercontent.com/32545163/67570647-ef190b00-f6ff-11e9-8268-3cd73465efae.png)

**There most be a way to do it with YAML, but I still don't know it**

**Comment by MooVC** [comment]
Any figured out how to do this in YAML?  I tried setting **persistCredentials: true** but it still fails.

**Comment by Good-man** [comment]
I figured it out.  Not only do you need persistCredentials: true (I think):
```
  steps:
  - checkout: self 
    persistCredentials: true
```
But you also need env: and SYSTEM_ACCESSTOKEN: $(System.AccessToken) as shown:
```
  - task: GitflowBranchGate@1
    inputs:
      repository: '$(Build.Repository.Name)'
      masterBranch: 'master'
      developBranch: 'develop'
      hotfixBranches: 'hotfix/*'
      releaseBranches: 'release/*'
      featureBranches: 'feature/*'
      hotfixBranchLimit: '1'
      hotfixBranchDaysLimit: '10'
      releaseBranchLimit: '1'
      releaseBranchDaysLimit: '10'
      featureBranchLimit: '50'
      featureBranchDaysLimit: '45'
      featureBranchesMustNotBeBehindMaster: false
      authenticationType: 'OAuthToken'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)      
```
