### ISSUE TITLE
Unable to Authenticate when using YAML Build

### ISSUE THREAD

**Issue by MooVC** [kerwinc/VSTSTasks#8]
I really love the features offered by this extension however, when I tried to integrate it with my build pipelines it fails due to an inability to read the repo.  Some investigation shows that the issue relates to an inability to obtain the OAuth token, but the setting needed to resolve this is not available, or does not work as intended, when using a YAML build definition.  The setting to which I refer is "Allow scripts to access the OAuth token" - I had thought that if I set persistCredentials: true that it would work but alas, to no avail.

Can you confirm if there is a known workaround for this, or perhaps correct me if I am misunderstanding the configuration?

**Comment by julioarruda** [comment]
This task work on yaml if you put this:

  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

And this step:
- checkout: self
  persistCredentials: true

**Comment by kerwinc** [comment]
@MooVC as @julioarruda mentioned, you need to allow the task to use the System.AccessToken. Has the above solution worked for you?

**Comment by MooVC** [comment]
> @MooVC as @julioarruda mentioned, you need to allow the task to use the System.AccessToken. Has the above solution worked for you?

Thanks for coming back on this one @kerwinc. I'm probably missing something here but when I did as suggested I get the following:

##[error]Could not find remote branch: refs/heads/master

- job: Integration
  timeoutInMinutes: 10
  pool:
    vmImage: windows-latest 
    workspace:
      clean: all
    checkout: self
    persistCredentials: true

  steps:

  - task: GitflowBranchGate@1
    inputs:
      repository: '$(Build.Repository.Name)'
      masterBranch: 'master'
      developBranch: 'develop'
      hotfixBranches: 'hotfix/*'
      releaseBranches: 'release/*'
      featureBranches: 'feature/*'
      hotfixBranchLimit: '1'
      hotfixBranchDaysLimit: '10'
      releaseBranchLimit: '1'
      releaseBranchDaysLimit: '10'
      featureBranchLimit: '50'
      featureBranchDaysLimit: '45'
      featureBranchesMustNotBeBehindDevelop: true
      authenticationType: 'OAuthToken'

**Comment by julioarruda** [comment]
The checkout and persist credentials is a step, not job configuration, and you need to declare env: on task


```yaml

steps:
- checkout: self
  persistCredentials: true

- task: GitflowBranchGate@1
  displayName: 'Gitflow Branch Gate'
  inputs:
    hotfixBranchLimit: 5
    hotfixBranchDaysLimit: 30
    releaseBranchLimit: 5
    releaseBranchDaysLimit: 365
    featureBranchLimit: 10
    featureBranchDaysLimit: 90
    hotfixBranchesMustNotHavePendingPullRequests: false
    releaseBranchesMustNotHavePendingPullRequests: false
    releaseMustNotBeBehindMaster: false
    mustNotHaveHotfixAndReleaseBranches: false
    featureBranchesMustNotBeBehindMaster: false
    CurrentFeatureMustNotBeBehindMaster: false
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```
