### ISSUE TITLE
Could not find remote branch: refs/heads/master in YAML pipeline

### ISSUE THREAD

**Issue by Good-man** [kerwinc/VSTSTasks#9]
Resurrecting [Issue #3](https://github.com/kerwinc/VSTSTasks/issues/3) 

I understand how to resolve this issue using the classic editor, but we want to use the YAML way instead.   Is there a way to Allow scripts to access the OAuth token in a YAML pipeline?

**Comment by Good-man** [comment]
I figured it out.  Not only do you need persistCredentials: true (I think):
```
  steps:
  - checkout: self 
    persistCredentials: true
```
But you also need env: and SYSTEM_ACCESSTOKEN: $(System.AccessToken) as shown:
```
  - task: GitflowBranchGate@1
    inputs:
      repository: '$(Build.Repository.Name)'
      masterBranch: 'master'
      developBranch: 'develop'
      hotfixBranches: 'hotfix/*'
      releaseBranches: 'release/*'
      featureBranches: 'feature/*'
      hotfixBranchLimit: '1'
      hotfixBranchDaysLimit: '10'
      releaseBranchLimit: '1'
      releaseBranchDaysLimit: '10'
      featureBranchLimit: '50'
      featureBranchDaysLimit: '45'
      featureBranchesMustNotBeBehindMaster: false
      authenticationType: 'OAuthToken'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)      
```
